# =============================================================================
# SCRIPT: Drop Index Procedures
#
# Purpose:
#   Drop all the non-primary key indexes for a given table. Pass in the table 
#   name as a parameter - <schema.table_name>
#
# Description:
#   To avoid having to hand code all the index drop commands for a table 
#   we collect them into a stored procedure  that drops the set of indexes 
#   around a given table.
#
#   We do not drop the primary key - only secondary indexes for tuning
#   reasons. Primary keys are declared in the LIQUIBASE files used to define the
#   schema.
#
# Release History:
#   Date     Who Changes Made
#   -------- --- --------------------------------------------------------------
#   14.02.17 NS  Version 1.0
#   18.05.17 TW  Debugged
#   23.05.17 TW  Added dv.SAT_BUS_HOLDBACK indexes
#   09.06.17 NS  Added source system and cdc indexes.
#   02.07.17 NS  Added link_booking_follows indexes
#   20.07.17 NS  Amended Sat effectivity index names, sat_eff._party index dropped
#   30.07.17 NS  Amended table names (effectivities) to align with standards, 
#                amended various table names to align with data model (booking
#                financials)
#   21.08.17 TW  Added statements for table SAT_TLINK_BOOKING_BOOKING_PARTY_ROLE_DETAILS
#   18.08.17 NS  Added AGENCY details, release 2.
#
# =============================================================================

DROP PROCEDURE IF EXISTS dv.DROP_INDEX;

------------------------------------
# procedure to drop indexes for a given table, one big case statement

DELIMITER //

CREATE PROCEDURE dv.DROP_INDEX (IN SCHEMANAME VARCHAR(100), IN TABLENAME VARCHAR(100))
BEGIN
DECLARE caseTable VARCHAR(255);
DECLARE msgText VARCHAR(255);
SET caseTable = concat(SCHEMANAME, '.', TABLENAME);
CASE caseTable

-- ------ release 1 indexes, BOOKING TABLE --------------------------------------------------------
    WHEN 'dv.HUB_BOOKING' THEN
        IF HAS_INDEX('dv', TABLENAME, 'BOOKING_SOURCE_INDEX') THEN
            ALTER TABLE  dv.HUB_BOOKING DROP INDEX BOOKING_SOURCE_INDEX;
        END IF;

    WHEN 'dv.HUB_PARTY' THEN
        IF HAS_INDEX('dv', TABLENAME, 'PARTY_SOURCE_INDEX') THEN
            ALTER TABLE dv.HUB_PARTY DROP INDEX PARTY_SOURCE_INDEX;
        END IF;

    WHEN 'dv.LINK_BOOKING_PARTY_ROLE' THEN
        IF HAS_INDEX('dv', TABLENAME, 'BOOKING_PARTY_ROLE_BOOKING_PARTY_INDEX') THEN
            ALTER TABLE dv.LINK_BOOKING_PARTY_ROLE DROP INDEX BOOKING_PARTY_ROLE_BOOKING_PARTY_INDEX;
        END IF;
        IF HAS_INDEX('dv', TABLENAME, 'BOOKING_PARTY_ROLE_PARTY_BOOKING_INDEX') THEN
            ALTER TABLE dv.LINK_BOOKING_PARTY_ROLE DROP INDEX BOOKING_PARTY_ROLE_PARTY_BOOKING_INDEX;
        END IF;
        IF HAS_INDEX('dv', TABLENAME, 'BOOKING_PARTY_ROLE_SOURCE_INDEX') THEN
            ALTER TABLE dv.LINK_BOOKING_PARTY_ROLE DROP INDEX BOOKING_PARTY_ROLE_SOURCE_INDEX;
        END IF;

    WHEN 'dv.SAT_TLINK_BOOKING_DETAILS' THEN
        IF HAS_INDEX('dv', TABLENAME, 'TLINK_BOOKING_DETAILS_CDC_INDEX') THEN
            ALTER TABLE dv.SAT_TLINK_BOOKING_DETAILS DROP INDEX TLINK_BOOKING_DETAILS_CDC_INDEX;
        END IF;
        IF HAS_INDEX('dv', TABLENAME, 'TLINK_BOOKING_DETAILS_SOURCE_INDEX') THEN
            ALTER TABLE dv.SAT_TLINK_BOOKING_DETAILS DROP INDEX TLINK_BOOKING_DETAILS_SOURCE_INDEX;
        END IF;

    WHEN 'dv.LINK_BOOKING_CONVERTS' THEN
        IF HAS_INDEX('dv', TABLENAME, 'BOOKING_QUOTE_INDEX') THEN
            ALTER TABLE dv.LINK_BOOKING_CONVERTS DROP INDEX BOOKING_QUOTE_INDEX;
        END IF;
        IF HAS_INDEX('dv', TABLENAME, 'QUOTE_BOOKING_INDEX') THEN
            ALTER TABLE dv.LINK_BOOKING_CONVERTS DROP INDEX QUOTE_BOOKING_INDEX;
        END IF;

    WHEN 'dv.SAT_TLINK_BOOKING_FINANCIALS' THEN
        IF HAS_INDEX('dv', TABLENAME, 'TLINK_BOOKING_FINANCIALS_CDC_INDEX') THEN
            ALTER TABLE dv.SAT_TLINK_BOOKING_FINANCIALS DROP INDEX TLINK_BOOKING_FINANCIALS_CDC_INDEX;
        END IF;
        IF HAS_INDEX('dv', TABLENAME, 'TLINK_BOOKING_FINANCIALS_SOURCE_INDEX') THEN
            ALTER TABLE dv.SAT_TLINK_BOOKING_FINANCIALS DROP INDEX TLINK_BOOKING_FINANCIALS_SOURCE_INDEX;
        END IF;

    WHEN 'dv.SAT_TLINK_BOOKING_PAX' THEN
        IF HAS_INDEX('dv', TABLENAME, 'TLINK_BOOKING_PAX_CDC_INDEX') THEN
            ALTER TABLE dv.SAT_TLINK_BOOKING_PAX DROP INDEX TLINK_BOOKING_PAX_CDC_INDEX;
        END IF;
        IF HAS_INDEX('dv', TABLENAME, 'TLINK_BOOKING_PAX_SOURCE_INDEX') THEN
            ALTER TABLE dv.SAT_TLINK_BOOKING_PAX DROP INDEX TLINK_BOOKING_PAX_SOURCE_INDEX;
        END IF;

    WHEN 'dv.SAT_TLINK_BOOKING_BOOKING_CONVERTS_EFFECTIVITY' THEN
        IF HAS_INDEX('dv', TABLENAME, 'TLINK_BOOKING_BOOKING_CONVERTS_EFFECTIVITY_CDC_INDEX') THEN
            ALTER TABLE dv.SAT_TLINK_BOOKING_BOOKING_CONVERTS_EFFECTIVITY DROP INDEX TLINK_BOOKING_BOOKING_CONVERTS_EFFECTIVITY_CDC_INDEX;
        END IF;
        IF HAS_INDEX('dv', TABLENAME, 'TLINK_BOOKING_CONVERTS_EFFECTIVITY_SOURCE_INDEX') THEN
            ALTER TABLE dv.SAT_TLINK_BOOKING_BOOKING_CONVERTS_EFFECTIVITY DROP INDEX TLINK_BOOKING_BOOKING_CONVERTS_EFFECTIVITY_SOURCE_INDEX;
        END IF;

    WHEN 'dv.SAT_TLINK_BOOKING_BOOKING_EFFECTIVITY' THEN
        IF HAS_INDEX('dv', TABLENAME, 'TLINK_BOOKING_BOOKING_EFFECTIVITY_CDC_INDEX') THEN
            ALTER TABLE dv.SAT_TLINK_BOOKING_BOOKING_EFFECTIVITY DROP INDEX TLINK_BOOKING_BOOKING_EFFECTIVITY_CDC_INDEX;
        END IF;
        IF HAS_INDEX('dv', TABLENAME, 'TLINK_BOOKING_BOOKING_EFFECTIVITY_SOURCE_INDEX') THEN
            ALTER TABLE dv.SAT_TLINK_BOOKING_BOOKING_EFFECTIVITY DROP INDEX TLINK_BOOKING_BOOKING_EFFECTIVITY_SOURCE_INDEX;
        END IF;

    WHEN 'dv.SAT_TLINK_BOOKING_BOOKING_PARTY_ROLE_EFFECTIVITY' THEN
        IF HAS_INDEX('dv', TABLENAME, 'TLINK_BOOKING_BOOKING_PARTY_ROLE_EFFECTIVITY_CDC_INDEX') THEN
            ALTER TABLE dv.SAT_TLINK_BOOKING_BOOKING_PARTY_ROLE_EFFECTIVITY DROP INDEX TLINK_BOOKING_BOOKING_PARTY_ROLE_EFFECTIVITY_CDC_INDEX;
        END IF;
        IF HAS_INDEX('dv', TABLENAME, 'TLINK_BOOKING_BOOKING_PARTY_ROLE_EFFECTIVITY_SOURCE_INDEX') THEN
            ALTER TABLE dv.SAT_TLINK_BOOKING_BOOKING_PARTY_ROLE_EFFECTIVITY DROP INDEX TLINK_BOOKING_BOOKING_PARTY_ROLE_EFFECTIVITY_SOURCE_INDEX;
        END IF;

    WHEN 'dv.SAT_TLINK_BOOKING_PARTY_EFFECTIVITY' THEN
        IF HAS_INDEX('dv', TABLENAME, 'TLINK_BOOKING_PARTY_EFFECTIVITY_CDC_INDEX') THEN
            ALTER TABLE dv.SAT_TLINK_BOOKING_PARTY_EFFECTIVITY DROP INDEX TLINK_BOOKING_PARTY_EFFECTIVITY_CDC_INDEX;
        END IF;
        IF HAS_INDEX('dv', TABLENAME, 'TLINK_BOOKING_PARTY_EFFECTIVITY_SOURCE_INDEX') THEN
            ALTER TABLE dv.SAT_TLINK_BOOKING_PARTY_EFFECTIVITY DROP INDEX TLINK_BOOKING_PARTY_EFFECTIVITY_SOURCE_INDEX;
        END IF;

    WHEN 'dv.SAT_TLINK_BOOKING_BOOKING_PARTY_ROLE_DETAILS' THEN
        IF HAS_INDEX('dv', TABLENAME, 'TLINK_BOOKING_BOOKING_PARTY_ROLE_DETAILS_CDC_INDEX') THEN
            ALTER TABLE dv.SAT_TLINK_BOOKING_BOOKING_PARTY_ROLE_DETAILS DROP INDEX TLINK_BOOKING_BOOKING_PARTY_ROLE_DETAILS_CDC_INDEX;
        END IF;
        IF HAS_INDEX('dv', TABLENAME, 'TLINK_BOOKING_BOOKING_PARTY_ROLE_DETAILS_SOURCE_INDEX') THEN
            ALTER TABLE dv.SAT_TLINK_BOOKING_BOOKING_PARTY_ROLE_DETAILS DROP INDEX TLINK_BOOKING_BOOKING_PARTY_ROLE_DETAILS_SOURCE_INDEX;
        END IF;

-- ------ release 2 indexes, AGENCY TABLE --------------------------------------------------------

    WHEN 'dv.HUB_LOCATOR' THEN
        IF HAS_INDEX('dv', TABLENAME, 'LOCATOR_SOURCE_INDEX') THEN
            ALTER TABLE dv.HUB_LOCATOR DROP INDEX LOCATOR_SOURCE_INDEX;
        END IF;

    WHEN 'dv.HUB_GEOGRAPHIC_AREA' THEN
        IF HAS_INDEX('dv', TABLENAME, 'GEOGRAPHIC_AREA_SOURCE_INDEX') THEN
            ALTER TABLE dv.HUB_GEOGRAPHIC_AREA DROP INDEX GEOGRAPHIC_AREA_SOURCE_INDEX;
        END IF;

    WHEN 'dv.LINK_PARTY_CONTACT' THEN
        IF HAS_INDEX('dv', TABLENAME, 'PARTY_CONTACT_PARTY_CONTACT_INDEX') THEN
            ALTER TABLE dv.LINK_PARTY_CONTACT DROP INDEX PARTY_CONTACT_PARTY_CONTACT_INDEX;
        END IF;
        IF HAS_INDEX('dv', TABLENAME, 'PARTY_CONTACT_CONTACT_PARTY_INDEX') THEN
            ALTER TABLE dv.LINK_PARTY_CONTACT DROP INDEX PARTY_CONTACT_CONTACT_PARTY_INDEX;
        END IF;
        IF HAS_INDEX('dv', TABLENAME, 'PARTY_CONTACT_SOURCE_INDEX') THEN
            ALTER TABLE dv.LINK_PARTY_CONTACT DROP INDEX PARTY_CONTACT_SOURCE_INDEX;
        END IF;

    WHEN 'dv.LINK_PARTY_GEOGRAPHIC_AREA' THEN
        IF HAS_INDEX('dv', TABLENAME, 'PARTY_GEOGRAPHIC_AREA_INDEX') THEN
            ALTER TABLE dv.LINK_PARTY_GEOGRAPHIC_AREA DROP INDEX PARTY_GEOGRAPHIC_AREA_INDEX;
        END IF;
        IF HAS_INDEX('dv', TABLENAME, 'GEOGRAPHIC_AREA_PARTY_INDEX') THEN
            ALTER TABLE dv.LINK_PARTY_GEOGRAPHIC_AREA DROP INDEX GEOGRAPHIC_AREA_PARTY_INDEX;
        END IF;
        IF HAS_INDEX('dv', TABLENAME, 'PARTY_GEOGRAPHIC_AREA_SOURCE_INDEX') THEN
            ALTER TABLE dv.LINK_PARTY_GEOGRAPHIC_AREA DROP INDEX PARTY_GEOGRAPHIC_AREA_SOURCE_INDEX;
        END IF;

    WHEN 'dv.SAT_TLINK_AGENCY_PARTY_DETAILS' THEN
        IF HAS_INDEX('dv', TABLENAME, 'TLINK_AGENCY_PARTY_DETAILS_CDC_INDEX') THEN
            ALTER TABLE dv.SAT_TLINK_AGENCY_PARTY_DETAILS DROP INDEX TLINK_AGENCY_PARTY_DETAILS_CDC_INDEX;
        END IF;
        IF HAS_INDEX('dv', TABLENAME, 'TLINK_AGENCY_PARTY_DETAILS_SOURCE_INDEX') THEN
            ALTER TABLE dv.SAT_TLINK_AGENCY_PARTY_DETAILS DROP INDEX TLINK_AGENCY_PARTY_DETAILS_SOURCE_INDEX;
        END IF;

    WHEN 'dv.SAT_TLINK_AGENCY_PARTY_EFFECTIVITY' THEN
        IF HAS_INDEX('dv', TABLENAME, 'TLINK_AGENCY_PARTY_EFFECTIVITY_CDC_INDEX') THEN
            ALTER TABLE dv.SAT_TLINK_AGENCY_PARTY_EFFECTIVITY DROP INDEX TLINK_AGENCY_PARTY_EFFECTIVITY_CDC_INDEX;
        END IF;
        IF HAS_INDEX('dv', TABLENAME, 'TLINK_AGENCY_PARTY_EFFECTIVITY_SOURCE_INDEX') THEN
            ALTER TABLE dv.SAT_TLINK_AGENCY_PARTY_EFFECTIVITY DROP INDEX TLINK_AGENCY_PARTY_EFFECTIVITY_SOURCE_INDEX;
        END IF;

    WHEN 'dv.SAT_TLINK_AGENCY_TELEPHONE' THEN
        IF HAS_INDEX('dv', TABLENAME, 'TLINK_AGENCY_TELEPHONE_CDC_INDEX') THEN
            ALTER TABLE dv.SAT_TLINK_AGENCY_TELEPHONE DROP INDEX TLINK_AGENCY_TELEPHONE_CDC_INDEX;
        END IF;
        IF HAS_INDEX('dv', TABLENAME, 'TLINK_AGENCY_TELEPHONE_SOURCE_INDEX') THEN
            ALTER TABLE dv.SAT_TLINK_AGENCY_TELEPHONE DROP INDEX TLINK_AGENCY_TELEPHONE_SOURCE_INDEX;
        END IF;

    WHEN 'dv.SAT_TLINK_AGENCY_PARTY_CONTACT' THEN
        IF HAS_INDEX('dv', TABLENAME, 'TLINK_AGENCY_PARTY_CONTACT_CDC_INDEX') THEN
            ALTER TABLE dv.SAT_TLINK_AGENCY_PARTY_CONTACT DROP INDEX TLINK_AGENCY_PARTY_CONTACT_CDC_INDEX;
        END IF;
        IF HAS_INDEX('dv', TABLENAME, 'TLINK_AGENCY_PARTY_CONTACT_SOURCE_INDEX') THEN
            ALTER TABLE dv.SAT_TLINK_AGENCY_PARTY_CONTACT DROP INDEX TLINK_AGENCY_PARTY_CONTACT_SOURCE_INDEX;
        END IF;

    WHEN 'dv.SAT_TLINK_AGENCY_PARTY_GEOGRAPHIC_AREA_EFFECTIVITY' THEN
        IF HAS_INDEX('dv', TABLENAME, 'TLINK_AGENCY_PARTY_GEOGRAPHIC_AREA_EFFECTIVITY_CDC_INDEX') THEN
            ALTER TABLE dv.SAT_TLINK_AGENCY_PARTY_GEOGRAPHIC_AREA_EFFECTIVITY DROP INDEX TLINK_AGENCY_PARTY_GEOGRAPHIC_AREA_EFFECTIVITY_CDC_INDEX;
        END IF;
        IF HAS_INDEX('dv', TABLENAME, 'TLINK_AGENCY_PARTY_GEOGRAPHIC_AREA_EFFECTIVITY_SOURCE_INDEX') THEN
            ALTER TABLE dv.SAT_TLINK_AGENCY_PARTY_GEOGRAPHIC_AREA_EFFECTIVITY DROP INDEX TLINK_AGENCY_PARTY_GEOGRAPHIC_AREA_EFFECTIVITY_SOURCE_INDEX;
        END IF;

    WHEN 'dv.SAT_TLINK_AGENCY_POSTAL_ADDRESS' THEN
        IF HAS_INDEX('dv', TABLENAME, 'TLINK_AGENCY_POSTAL_ADDRESS_CDC_INDEX') THEN
            ALTER TABLE dv.SAT_TLINK_AGENCY_POSTAL_ADDRESS DROP INDEX TLINK_AGENCY_POSTAL_ADDRESS_CDC_INDEX;
        END IF;
        IF HAS_INDEX('dv', TABLENAME, 'TLINK_AGENCY_POSTAL_ADDRESS_SOURCE_INDEX') THEN
            ALTER TABLE dv.SAT_TLINK_AGENCY_POSTAL_ADDRESS DROP INDEX TLINK_AGENCY_POSTAL_ADDRESS_SOURCE_INDEX;
        END IF;

    WHEN 'dv.SAT_TLINK_AGENCY_LOCATOR_EFFECTIVITY' THEN
        IF HAS_INDEX('dv', TABLENAME, 'TLINK_AGENCY_LOCATOR_EFFECTIVITY_CDC_INDEX') THEN
            ALTER TABLE dv.SAT_TLINK_AGENCY_LOCATOR_EFFECTIVITY DROP INDEX TLINK_AGENCY_LOCATOR_EFFECTIVITY_CDC_INDEX;
        END IF;
        IF HAS_INDEX('dv', TABLENAME, 'TLINK_AGENCY_LOCATOR_EFFECTIVITY_SOURCE_INDEX') THEN
            ALTER TABLE dv.SAT_TLINK_AGENCY_LOCATOR_EFFECTIVITY DROP INDEX TLINK_AGENCY_LOCATOR_EFFECTIVITY_SOURCE_INDEX;
        END IF;

    WHEN 'dv.SAT_TLINK_AGENCY_PARTY_CONTACT_EFFECTIVITY' THEN
        IF HAS_INDEX('dv', TABLENAME, 'TLINK_AGENCY_PARTY_CONTACT_EFFECTIVITY_CDC_INDEX') THEN
            ALTER TABLE dv.SAT_TLINK_AGENCY_PARTY_CONTACT_EFFECTIVITY DROP INDEX TLINK_AGENCY_PARTY_CONTACT_EFFECTIVITY_CDC_INDEX;
        END IF;
        IF HAS_INDEX('dv', TABLENAME, 'TLINK_AGENCY_PARTY_CONTACT_EFFECTIVITY_SOURCE_INDEX') THEN
            ALTER TABLE dv.SAT_TLINK_AGENCY_PARTY_CONTACT_EFFECTIVITY DROP INDEX TLINK_AGENCY_PARTY_CONTACT_EFFECTIVITY_SOURCE_INDEX;
        END IF;

-- ------ end - no table recognised ---------------------------------------------------------------

    ELSE
            SET msgText = concat('Table ', caseTable, ' not found in drop_index procedure.');
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = msgText;
    
    END CASE;

END //

DELIMITER ;
