# =========================================================================================================================================
# SCRIPT TO INSERT DATA VAULT LOADER METADATA
#
# Description:
#  This script inserts Vault loader metadata into the control tables used to drive the Data Vault generic loader. It is organised into 
#  separate sections for each source table, arranged alphabetically. Within each section are subsections containing inserts for each
#  table driving a different step of the load.
#
# Note:
#  Using double quoted data values to support data values containing single quotes
#
# Release History:
#   Date     Who Changes Made
#   -------- --- --------------------------------------------------------------------------------------------------------------------------
#   28.04.17 NS  Added insert Talend Jobs data. Modified booking hashes so they do not hash the party role type, amended link mappings
#                so they use the unhashed party role values (role of customer and brand/supplier), set most talend jobs to inactive so 
#                only the booking load is working.
#   19.05.17 TW  Debugged
#   23.05.17 NS  Amended hashing and fk_delete data to process PARTY_ROLE and PRODUCT_ROLE as literals, not as hashes.
#   26.05.17 NS  Typo in BOOKING hash calculation, double entry of product party key fields, removed.
#   02.07.17 NS  Added link_booking_converts, added lead and quote number fields to booking metadata with associated hashing.
#   20.07.17 NS  Amended Sat effectivity names, sat_eff._party dropped
#   30.07.17 NS  Amended 
#   11.08.17 TW  Correct typos
#   14.08.17 TW  New TALEND_JOBS records for TLINK WH table replication jobs
#   16.08.17 TW  In HASHES changed LOCALCURRENCY to LOCAL_CURRENCY
#   16.08.17 TW  In HUBS changed LEAD_HASH to PASSENGER_HASH
#   16.08.17 TW  In SATELLITES, SAT_TLINK_BOOKING_DETAILS, changed CANX_DATE to CANCELLATION_DATE, STATUS to STATUS_CODE
#                and moved LOCAL_CURRENCY and TOMSRATE to SAT_TLINK_BOOKING_FINANCIALS  
#   16.08.17 TW  In SATELLITES, SAT_TLINK_BOOKING_FINANCIALS, changed BOOKING_MARGIN to MARGIN_AMOUNT, TOTAL_COSTS to TOTAL_COST
#   16.08.17 TW  In SATELLITES, SAT_TLINK_BOOKING_PAX, corrected the target payload columns
#   16.08.17 TW  In SATELLITES, SAT_TLINK_BOOKING_BOOKING_CONVERTS_EFFECTIVITY corrected typo in target table name
#   21.08.17 NS  Added metadata for table SAT_TLINK_BOOKING_BOOKING_PARTY_ROLE_DETAILS
#   21.08.17 NS  Added metadata for release 1.002, Agency
#
# =========================================================================================================================================

# -----------------------------------------------------------------------------------------------------------------------------------------
# TRUNCATE EXISTING DATA
# -----------------------------------------------------------------------------------------------------------------------------------------
truncate ctrl.TALEND_JOBS;
truncate ctrl.VAULT_LOAD_HASHES;
truncate ctrl.VAULT_LOAD_HUBS;
truncate ctrl.VAULT_LOAD_LINKS;
truncate ctrl.VAULT_LOAD_SATS;
truncate ctrl.VAULT_DELETES;
truncate ctrl.VAULT_DELETE_EFFECTIVITY;
truncate ctrl.VAULT_DELETE_FK_LINK_EFFECTIVITY;

# =========================================================================================================================================
# JOB CONTROL DATA - PARAMETERS PASSED INTO VAULT ETL JOBS THAT DETERMINE WHAT JOBS RUN, WHERE TARGET AND SOURCE DATABASES ARE LOCATED
# TEXT TO USE WHEN LOGGING ACTIVITY, AND THE NAMES OF THE TALEND JOBS TO RUN
# =========================================================================================================================================

insert into ctrl.TALEND_JOBS (JOB_NAME, JOB_DESC, ACTIVE, SRC_TABLE_NAME, LOAD_TYPE, TABLE_TYPE, SOURCE_SYSTEM_NAME, SOURCE_TABLE_NAME, HIVE_TABLE, TALEND_JOB_NAME)
values
     ("AGENCY_SNP", "Agency initial load", 0, "STG_AGENCY", "SNP", "SNP/UPD/DEL", "TRAVELINK", "AGENCY", "agency", "J1100_Agency_Load_Generic")
    ,("AGENCY_REG", "Agency regular load", 0, "STG_AGENCY", "REG", "SNP/UPD/DEL", "TRAVELINK", "AGENCY", "agency", "J1100_Agency_Load_Generic")
    ,("BOOKINGS_SNP", "Bookings initial load", 1, "STG_BOOKINGS", "SNP", "SNP/UPD/DEL", "TRAVELINK", "BOOKINGS", "bookings", "J1110_Bookings_Load_Generic")
    ,("BOOKINGS_REG", "Bookings regular load", 1, "STG_BOOKINGS", "REG", "SNP/UPD/DEL", "TRAVELINK", "BOOKINGS", "bookings", "J1110_Bookings_Load_Generic")
    ,("COUNTRIES_SNP", "Countries initial load", 0, "STG_COUNTRIES", "SNP", "SNP/UPD/DEL", "TRAVELINK", "COUNTRIES", "countries", "J1120_Countries_Load_Generic")
    ,("COUNTRIES_REG", "Countries regular load", 0, "STG_COUNTRIES", "REG", "SNP/UPD/DEL", "TRAVELINK", "COUNTRIES", "countries", "J1120_Countries_Load_Generic")
    ,("SUBREGIONS_SNP", "Subregions initial load", 0, "STG_SUBREGIONS", "SNP", "SNP/UPD/DEL", "TRAVELINK", "SUBREGIONS", "subregions", "J1130_Subregions_Load_Generic")
    ,("SUBREGIONS_REG", "Subregions regular load", 0, "STG_SUBREGIONS", "REG", "SNP/UPD/DEL", "TRAVELINK", "SUBREGIONS", "subregions", "J1130_Subregions_Load_Generic")
    ,("RESORTS_SNP", "Resort initial load", 0, "STG_RESORT", "SNP", "SNP/UPD/DEL", "TRAVELINK", "RESORT", "resort", "J1140_Resort_Load_Generic")
    ,("RESORTS_REG", "Resort regular load", 0, "STG_RESORT", "REG", "SNP/UPD/DEL", "TRAVELINK", "RESORT", "resort", "J1140_Resort_Load_Generic")
    ,("PAX_KPI_SNP", "PAX KPI full load", 0, "STG_PAX", "SNP", "BUSINESS_RULE", "VAULT", "BUSINESS_RULE", NULL, "J1500_PAX_KPI_Load_Generic")
    ,("PAX_KPI_REG", "PAX KPI recent load", 0, "STG_PAX", "REG", "BUSINESS_RULE", "VAULT", "BUSINESS_RULE", NULL, "J1500_PAX_KPI_Load_Generic")
    ,("HOLIDAYMASTERRECORD_SNP", "Holiday_Master_Record initial load", 0, "STG_HOLIDAY_MASTER_RECORD", "SNP", "SNP/UPD/DEL", "TRAVELINK", "HOLIDAYMASTERRECORD", "holidaymasterrecord", "J1150_Holiday_Master_Record_Load_Generic")
    ,("HOLIDAYMASTERRECORD_REG", "Holiday_Master_Record initial load", 0, "STG_HOLIDAY_MASTER_RECORD", "REG", "SNP/UPD/DEL", "TRAVELINK", "HOLIDAYMASTERRECORD", "holidaymasterrecord", "J1150_Holiday_Master_Record_Load_Generic")
    ,("HOLIDAYUNITRECORD_SNP", "Holiday_Unit_Record initial load", 0, "STG_HOLIDAYUNITRECORD", "SNP", "SNP/UPD/DEL", "TRAVELINK", "HOLIDAYUNITRECORD", "holidayunitrecord", "J1160_Holiday_Unit_Record_Load_Generic")
    ,("HOLIDAYUNITRECORD_REG", "Holiday_Unit_Record initial load", 0, "STG_HOLIDAYUNITRECORD", "REG", "SNP/UPD/DEL", "TRAVELINK", "HOLIDAYUNITRECORD", "holidayunitrecord", "J1160_Holiday_Unit_Record_Load_Generic")
    ,("HOLDBACKS_SNP", "Holdbacks full load", 0, "STG_BUS_HOLDBACK", "SNP", "BUSINESS_RULE", "VAULT", "BUSINESS_RULE", NULL, "J1510_Holdbacks_Load_Generic")
    ,("HOLDBACKS_REG", "Holdbacks recent load", 0, "STG_BUS_HOLDBACK", "REG", "BUSINESS_RULE", "VAULT", "BUSINESS_RULE", NULL, "J1510_Holdbacks_Load_Generic")
    ,("AGENCY_GROUP_SNP", "Agency Group initial load", 0, "STG_AGENCY_GROUP", "SNP", "SNP/UPD/DEL", "TRAVELINK", "AGENCYGROUP", "agencygroup", "J1170_Agency_Group_Load_Generic")
    ,("AGENCY_GROUP_REG", "Agency Group regular load", 0, "STG_AGENCY_GROUP", "REG", "SNP/UPD/DEL", "TRAVELINK", "AGENCYGROUP", "agencygroup", "J1170_Agency_Group_Load_Generic")
    ,("ACCOM_DET_SNP", "Accom Det initial load", 0, "STG_ACCOM_DET", "SNP", "SNP/UPD/DEL", "TRAVELINK", "ACCOMDET", "accom_det", "J1180_Accom_Det_Load_Generic")
    ,("ACCOM_DET_REG", "Accom Det regular load", 0, "STG_ACCOM_DET", "REG", "SNP/UPD/DEL", "TRAVELINK", "ACCOMDET", "accom_det", "J1180_Accom_Det_Load_Generic")
    ,("FLIGHT_DET_SNP", "Flight Det initial load", 0, "STG_FLIGHT_DET", "SNP", "SNP/UPD/DEL", "TRAVELINK", "FLIGHTDET", "flight_det", "J1190_Flight_Det_Load_Generic")
    ,("FLIGHT_DET_REG", "Flight Det regular load", 0, "STG_FLIGHT_DET", "REG", "SNP/UPD/DEL", "TRAVELINK", "FLIGHTDET", "flight_det", "J1190_Flight_Det_Load_Generic")
    ,("FLIGHTS_SNP", "Flights initial load", 0, "STG_FLIGHTS", "SNP", "SNP/UPD/DEL", "TRAVELINK", "FLIGHTS", "flights", "J1200_Flights_Load_Generic")
    ,("FLIGHTS_REG", "Flights regular load", 0, "STG_FLIGHTS", "REG", "SNP/UPD/DEL", "TRAVELINK", "FLIGHTS", "flights", "J1200_Flights_Load_Generic")
    ,("LINKPAXFLIGHTS_SNP", "Link PAX to Flights initial load", 0, "STG_LINK_PAX_FLIGHTS", "SNP", "SNP/UPD/DEL", "TRAVELINK", "LINKPAXTOFLIGHTS", "linkpaxtoflights", "J1210_LinkPAXtoFlights_Load_Generic")
    ,("LINKPAXFLIGHTS_REG", "Link PAX to Flights regular load", 0, "STG_LINK_PAX_FLIGHTS", "REG", "SNP/UPD/DEL", "TRAVELINK", "LINKPAXTOFLIGHTS", "linkpaxtoflights", "J1210_LinkPAXtoFlights_Load_Generic")
    ,("LINKPAXROOMS_SNP", "Link PAX to Rooms initial load", 0, "STG_LINK_PAX_ROOMS", "SNP", "SNP/UPD/DEL", "TRAVELINK", "LINKPAXTOROOMS", "linkpaxtorooms", "J1220_LinkPAXtoRooms_Load_Generic")
    ,("LINKPAXROOMS_REG", "Link PAX to Rooms regular load", 0, "STG_LINK_PAX_ROOMS", "REG", "SNP/UPD/DEL", "TRAVELINK", "LINKPAXTOROOMS", "linkpaxtorooms", "J1220_LinkPAXtoRooms_Load_Generic")
    ,("PASSENGERS_SNP", "Passengers initial load", 0, "STG_PASSENGERS", "SNP", "SNP/UPD/DEL", "TRAVELINK", "PASSENGERS", "passengers", "J1230_Passengers_Load_Generic")
    ,("PASSENGERS_REG", "Passengers regular load", 0, "STG_PASSENGERS", "REG", "SNP/UPD/DEL", "TRAVELINK", "PASSENGERS", "passengers", "J1230_Passengers_Load_Generic")
    ,("PROJECTS_SNP", "Projects initial load", 0, "STG_PROJECTS", "SNP", "SNP/UPD/DEL", "TRAVELINK", "PROJECTS", "projects", "J1240_Projects_Load_Generic")
    ,("PROJECTS_REG", "Projects regular load", 0, "STG_PROJECTS", "REG", "SNP/UPD/DEL", "TRAVELINK", "PROJECTS", "projects", "J1240_Projects_Load_Generic")
    ,("SUPPLIERS_SNP", "Suppliers initial load", 0, "STG_SUPPLIERS", "SNP", "SNP/UPD/DEL", "TRAVELINK", "SUPPLIERS", "suppliers", "J1250_Suppliers_Load_Generic")
    ,("SUPPLIERS_REG", "Suppliers regular load", 0, "STG_SUPPLIERS", "REG", "SNP/UPD/DEL", "TRAVELINK", "SUPPLIERS", "suppliers", "J1250_Suppliers_Load_Generic")
    ,("TOMS_SNP", "TOMS initial load", 0, "STG_MI_TOMS", "SNP", "SNP/UPD/DEL", "TRAVELINK", "VIEW_EUR_MI_TOMS", "view_eur_mi_toms", "J1260_TOMS_Load_Generic")
    ,("TOMS_REG", "TOMS regular load", 0, "STG_MI_TOMS", "REG", "SNP/UPD/DEL", "TRAVELINK", "VIEW_EUR_MI_TOMS", "view_eur_mi_toms", "J1260_TOMS_Load_Generic")
    ,("BRANCH_DIM_REG","BRANCH_DIM initial and regular full load",1,"BRANCH_DIM","REGFULL","TLINKWH","TLINKWH","BRANCH_DIM",NULL,"BRANCH_DIM")
    ,("COUNTRY_DIM_REG","COUNTRY_DIM initial and regular full load",1,"COUNTRY_DIM","REGFULL","TLINKWH","TLINKWH","COUNTRY_DIM",NULL,"COUNTRY_DIM")
    ,("DIFFERENTIATED_ACCOM_REG","DIFFERENTIATED_ACCOM initial and regular full load",1,"DIFFERENTIATED_ACCOM","REGFULL","TLINKWH","TLINKWH","DIFFERENTIATED_ACCOM",NULL,"DIFFERENTIATED_ACCOM")
    ,("DYNAMICS_EXTRA_TYPE_REG","DYNAMICS_EXTRA_TYPE initial and regular full load",1,"DYNAMICS_EXTRA_TYPE","REGFULL","TLINKWH","TLINKWH","DYNAMICS_EXTRA_TYPE",NULL,"DYNAMICS_EXTRA_TYPE")
    ,("FLIGHT_CLASS_DIM_REG","FLIGHT_CLASS_DIM initial and regular full load",1,"FLIGHT_CLASS_DIM","REGFULL","TLINKWH","TLINKWH","FLIGHT_CLASS_DIM",NULL,"FLIGHT_CLASS_DIM")
    ,("GATEWAY_DIM_REG","GATEWAY_DIM initial and regular full load",1,"GATEWAY_DIM","REGFULL","TLINKWH","TLINKWH","GATEWAY_DIM",NULL,"GATEWAY_DIM")
    ,("PRIMARY_COUNTRY_DIM_REG","PRIMARY_COUNTRY_DIM initial and regular full load",1,"PRIMARY_COUNTRY_DIM","REGFULL","TLINKWH","TLINKWH","PRIMARY_COUNTRY_DIM",NULL,"PRIMARY_COUNTRY_DIM")
    ,("REGION_DIV_DIM_REG","REGION_DIV_DIM initial and regular full load",1,"REGION_DIV_DIM","REGFULL","TLINKWH","TLINKWH","REGION_DIV_DIM",NULL,"REGION_DIV_DIM")
    ,("RESP_DT_AGENT_REG","RESP_DT_AGENT initial and regular full load",1,"RESP_DT_AGENT","REGFULL","TLINKWH","TLINKWH","RESP_DT_AGENT",NULL,"RESP_DT_AGENT")
    ,("RESP_DT_CLW_REG","RESP_DT_CLW initial and regular full load",1,"RESP_DT_CLW","REGFULL","TLINKWH","TLINKWH","RESP_DT_CLW",NULL,"RESP_DT_CLW")
    ,("RESP_DT_SKILL_REG","RESP_DT_SKILL initial and regular full load",1,"RESP_DT_SKILL","REGFULL","TLINKWH","TLINKWH","RESP_DT_SKILL",NULL,"RESP_DT_SKILL")
    ,("RESP_DT_SKILLX_REG","RESP_DT_SKILLX initial and regular full load",1,"RESP_DT_SKILLX","REGFULL","TLINKWH","TLINKWH","RESP_DT_SKILLX",NULL,"RESP_DT_SKILLX")
    ,("RESP_DT_VDN_REG","RESP_DT_VDN initial and regular full load",1,"RESP_DT_VDN","REGFULL","TLINKWH","TLINKWH","RESP_DT_VDN",NULL,"RESP_DT_VDN")
    ,("SPECIALIST_FORECAST_REG","SPECIALIST_FORECAST initial and regular full load",1,"SPECIALIST_FORECAST","REGFULL","TLINKWH","TLINKWH","SPECIALIST_FORECAST",NULL,"SPECIALIST_FORECAST")
    ,("T_TL_W_AGENCY_REG","T_TL_W_AGENCY initial and regular full load",1,"T_TL_W_AGENCY","REGFULL","TLINKWH","TLINKWH","T_TL_W_AGENCY",NULL,"T_TL_W_AGENCY")
    ,("TL_W_ACCOM_UNITS_REG","TL_W_ACCOM_UNITS initial and regular full load",1,"TL_W_ACCOM_UNITS","REGFULL","TLINKWH","TLINKWH","TL_W_ACCOM_UNITS",NULL,"TL_W_ACCOM_UNITS")
    ,("TL_W_AGENCY_REG","TL_W_AGENCY initial and regular ful load",1,"TL_W_AGENCY","REGFULL","TLINKWH","TLINKWH","TL_W_AGENCY",NULL,"TL_W_AGENCY")
    ,("TL_W_AIRLINES_REG","TL_W_AIRLINES initial and regular full load",1,"TL_W_AIRLINES","REGFULL","TLINKWH","TLINKWH","TL_W_AIRLINES",NULL,"TL_W_AIRLINES")
    ,("TL_W_AIRPORTS_REG","TL_W_AIRPORTS initial and regular full load",1,"TL_W_AIRPORTS","REGFULL","TLINKWH","TLINKWH","TL_W_AIRPORTS",NULL,"TL_W_AIRPORTS")
    ,("TL_W_HOLDBACKS_NEW_REG","TL_W_HOLDBACKS_NEW initial and regular full load",1,"TL_W_HOLDBACKS_NEW","REGFULL","TLINKWH","TLINKWH","TL_W_HOLDBACKS_NEW",NULL,"TL_W_HOLDBACKS_NEW")
    ,("TL_W_RESORTREGIONCOUNTRYVIEW_REG","TL_W_RESORTREGIONCOUNTRYVIEW initial and regular full load",1,"TL_W_RESORTREGIONCOUNTRYVIEW","REGFULL","TLINKWH","TLINKWH","TL_W_RESORTREGIONCOUNTRYVIEW",NULL,"TL_W_RESORTREGIONCOUNTRYVIEW")
    ,("TLINK_DAYDIMENSION_REG","TLINK_DAYDIMENSION initial and regular full load",1,"TLINK_DAYDIMENSION","REGFULL","TLINKWH","TLINKWH","TLINK_DAYDIMENSION",NULL,"TLINK_DAYDIMENSION")
    ,("TL_W_BOOKINGCOSTS_REG","TL_W_BOOKINGCOSTS regular frame load",1,"TL_W_BOOKINGCOSTS","REGFRAME","TLINKWH","TLINKWH","TL_W_BOOKINGCOSTS",NULL,"TL_W_BOOKINGCOSTS_RF")
    ,("TL_W_BOOKINGPRICES_REG","TL_W_BOOKINGPRICES regular frame load",1,"TL_W_BOOKINGPRICES","REGFRAME","TLINKWH","TLINKWH","TL_W_BOOKINGPRICES",NULL,"TL_W_BOOKINGPRICES_RF")
    ,("TL_W_BOOKEDEXTRAS_REG","TL_W_BOOKEDEXTRAS regular frame load",1,"TL_W_BOOKEDEXTRAS","REGFRAME","TLINKWH","TLINKWH","TL_W_BOOKEDEXTRAS",NULL,"TL_W_BOOKEDEXTRAS_RF")
    ,("TL_W_BOOKEDFLIGHTS_REG","TL_W_BOOKEDFLIGHTS regular frame load",1,"TL_W_BOOKEDFLIGHTS","REGFRAME","TLINKWH","TLINKWH","TL_W_BOOKEDFLIGHTS",NULL,"TL_W_BOOKEDFLIGHTS_RF")
    ,("TL_W_BOOKEDACCOMMODATION_REG","TL_W_BOOKEDACCOMMODATION regular frame load",1,"TL_W_BOOKEDACCOMMODATION","REGFRAME","TLINKWH","TLINKWH","TL_W_BOOKEDACCOMMODATION",NULL,"TL_W_BOOKEDACCOMMODATION_RF")
    ,("TL_W_BOOKEDTRANSFERS_REG","TL_W_BOOKEDTRANSFERS regular frame load",1,"TL_W_BOOKEDTRANSFERS","REGFULL","REGFRAME","TLINKWH","TL_W_BOOKEDTRANSFERS",NULL,"TL_W_BOOKEDTRANSFERS_RF")
    ,("TL_W_BOOKINGCOMMENTS_REG","TL_W_BOOKINGCOMMENTS regular frame load",1,"TL_W_BOOKINGCOMMENTS","REGFULL","REGFRAME","TLINKWH","TL_W_BOOKINGCOMMENTS",NULL,"TL_W_BOOKINGCOMMENTS_RF")
    ,("TL_W_BOOKINGS_REG","TL_W_BOOKINGS regular frame load",1,"TL_W_BOOKINGS","REGFRAME","TLINKWH","TLINKWH","TL_W_BOOKINGS",NULL,"TL_W_BOOKINGS_RF")
    ,("TL_W_PASSENGERS_REG","TL_W_PASSENGERS regular frame load",1,"TL_W_PASSENGERS","REGFRAME","TLINKWH","TLINKWH","TL_W_PASSENGERS",NULL,"TL_W_PASSENGERS_RF")
    ,("TL_W_BOOKINGS_TOMS_REG","TL_W_BOOKINGS_TOMS regular frame load",1,"TL_W_BOOKINGS_TOMS","REGFRAME","TLINKWH","TLINKWH","TL_W_BOOKINGS_TOMS",NULL,"TL_W_BOOKINGS_TOMS_RF")
    ,("TL_W_BOOKEDCARHIRE_REG","TL_W_BOOKEDCARHIRE regular frame load",1,"TL_W_BOOKEDCARHIRE","REGFRAME","TLINKWH","TLINKWH","TL_W_BOOKEDCARHIRE",NULL,"TL_W_BOOKEDCARHIRE_RF")
    ,("TL_W_FLIGHTCONTRACTS_REG","TL_W_FLIGHTCONTRACTS regular frame load",1,"TL_W_FLIGHTCONTRACTS","REGFRAME","TLINKWH","TLINKWH","TL_W_FLIGHTCONTRACTS",NULL,"TL_W_FLIGHTCONTRACTS_RF")
    ,("TL_W_ACCOMROUTE_REG","TL_W_ACCOMROUTE regular frame load",1,"TL_W_ACCOMROUTE","REGFULL","TLINKWH","TLINKWH","TL_W_ACCOMROUTE",NULL,"TL_W_ACCOMROUTE")
    ,("TL_W_BOOKINGS_DIM_DATA_REG","TL_W_BOOKINGS_DIM_DATA regular frame load",1,"TL_W_BOOKINGS_DIM_DATA","REGFRAME","TLINKWH","TLINKWH","TL_W_BOOKINGS_DIM_DATA",NULL,"TL_W_BOOKINGS_DIM_DATA_RF")
    ,("CMS_W_HSPLIT_REG","CMS_W_HSPLIT regular frame load",1,"CMS_W_HSPLIT","REGFRAME","TLINKWH","TLINKWH","CMS_W_HSPLIT",NULL,"CMS_W_HSPLIT_RC")
    ,("CMS_W_DAGENT_REG","CMS_W_DAGENT regular frame load",1,"CMS_W_DAGENT","REGFRAME","TLINKWH","TLINKWH","CMS_W_DAGENT",NULL,"CMS_W_DAGENT_RC")
    ,("CMS_W_DSPLIT_REG","CMS_W_DSPLIT regular frame load",1,"CMS_W_DSPLIT","REGFRAME","TLINKWH","TLINKWH","CMS_W_DSPLIT",NULL,"CMS_W_DSPLIT_RC")
    ,("CMS_W_DVDN_REG","CMS_W_DVDN regular frame load",1,"CMS_W_DVDN","REGFRAME","TLINKWH","TLINKWH","CMS_W_DVDN",NULL,"CMS_W_DVDN_RC")
    ;

# =========================================================================================================================================
# TRAVELINK DATA
# =========================================================================================================================================

# -----------------------------------------------------------------------------------------------------------------------------------------
# TRAVELINK - BOOKINGS
# -----------------------------------------------------------------------------------------------------------------------------------------

# HASHES ----------------------------------
insert into ctrl.VAULT_LOAD_HASHES (SRC_SYSTEM_NAME, SRC_TABLE_NAME, HASH_RUN_SEQUENCE, TGT_TABLE_NAME, COLUMNS_USED_FOR_HASH, TGT_HASH_COLUMN)
values
    ("TLINK", "STG_BOOKINGS", 1, "STG_BOOKINGS", "'TLINK-BRAND-CODES',PRODUCT", "SUPPLIER_HASH"), -- for hub parties, supplier records
    ("TLINK", "STG_BOOKINGS", 2, "STG_BOOKINGS", "'TLINK-CUSTOMER-CODES',AGENCY", "CUSTOMER_HASH"),   --  for hub parties, customer records
    ("TLINK", "STG_BOOKINGS", 3, "STG_BOOKINGS", "'TLINK-PASSENGER-CODES',LEAD", "PASSENGER_HASH"),   -- for lead passenger
    ("TLINK", "STG_BOOKINGS", 4, "STG_BOOKINGS", "'TLINK-BOOKING-CODES',BCODE", "BOOKING_HASH"),  -- for hub_booking
    ("TLINK", "STG_BOOKINGS", 5, "STG_BOOKINGS", "'TLINK-QUOTE-CODES',QUOTE_NUMBER", "QUOTE_HASH"),   -- for linked quotes
    ("TLINK", "STG_BOOKINGS", 6, "STG_BOOKINGS", "'TLINK-BOOKING-CODES', BCODE, 'TLINK-QUOTE-CODES',QUOTE_NUMBER", "BOOKING_CONVERTS_HASH"),   -- for linking bookings to quotes, conversions
    ("TLINK", "STG_BOOKINGS", 7, "STG_BOOKINGS", "'TLINK-BOOKING-CODES',BCODE,'TLINK-BRAND-CODES',PRODUCT,'SUPPLIER'", "BPR_SUPPLIER_HASH"), -- BOOKING_HASH, product, product hash, supplier
    ("TLINK", "STG_BOOKINGS", 8, "STG_BOOKINGS", "'TLINK-BOOKING-CODES',BCODE,'TLINK-CUSTOMER-CODES',AGENCY,'CUSTOMER'", "BPR_CUSTOMER_HASH"),  -- BOOKING_HASH, party_hash
    ("TLINK", "STG_BOOKINGS", 9, "STG_BOOKINGS", "'TLINK-BOOKING-CODES', BCODE, 'TLINK-PASSENGER-CODES',LEAD, 'PASSENGER'", "BPR_PASSENGER_HASH"),   -- for linking booking to lead passenger
    ("TLINK", "STG_BOOKINGS",10, "STG_BOOKINGS", "BDATE,BOOKEDBY,CANXDATE,CONFIRMDATE,DEPARTUREDATE,DURATION,STATUS", "BOOKING_DETAILS_PAYLOAD_HASH"),  -- for sat booking details
    ("TLINK", "STG_BOOKINGS",11, "STG_BOOKINGS", "ADJ,BALANCEDATE,COM,DEP,DUE,LOCAL_CURRENCY,MARGIN,PAY,TOMSRATE,TOT,TOTALCOSTS,VAT", "BOOKING_FINANCIALS_PAYLOAD_HASH"),  -- for sat booking costs
    ("TLINK", "STG_BOOKINGS",12, "STG_BOOKINGS", "ADULTS,CHILDREN,INFANTS,PAXNUM,SEATS", "BOOKING_PAX_PAYLOAD_HASH"),   -- for sat booking pax
    ("TLINK", "STG_BOOKINGS",13, "STG_BOOKINGS", "'1'", "BOOKING_PARTY_PASSENGER_PAYLOAD_HASH");   -- for is_lead passenger

# HUBS ------------------------------------
insert into ctrl.VAULT_LOAD_HUBS
    (SRC_SYSTEM_NAME, SRC_TABLE_NAME, HUB_RUN_SEQUENCE, SRC_HUB_TABLE_NAME, TGT_HUB_TABLE_NAME, SRC_PK, TGT_PK, SRC_NK, TGT_NK)
values
    ("TLINK", "BOOKINGS", 1, "STG_BOOKINGS", "HUB_BOOKING", "BOOKING_HASH", "BOOKING_HASH", " 'TLINK-BOOKING-CODES',BCODE", "IDENTIFIER_SET, BOOKING_REFERENCE"),
    ("TLINK", "BOOKINGS", 2, "STG_BOOKINGS", "HUB_PARTY", "CUSTOMER_HASH", "PARTY_HASH", " 'TLINK-CUSTOMER-CODES',AGENCY", "IDENTIFIER_SET,PARTY_IDENTIFIER"),
    ("TLINK", "BOOKINGS", 3, "STG_BOOKINGS", "HUB_PARTY", "SUPPLIER_HASH", "PARTY_HASH", " 'TLINK-BRAND-CODES',PRODUCT", "IDENTIFIER_SET,PARTY_IDENTIFIER"),
    ("TLINK", "BOOKINGS", 4, "STG_BOOKINGS", "HUB_PARTY", "PASSENGER_HASH", "PARTY_HASH", " 'TLINK-PASSENGER-CODES',LEAD", "IDENTIFIER_SET,PARTY_IDENTIFIER"),
    ("TLINK", "BOOKINGS", 5, "STG_BOOKINGS", "HUB_BOOKING", "QUOTE_HASH", "BOOKING_HASH", " 'TLINK-QUOTE-CODES',QUOTE_NUMBER", "IDENTIFIER_SET,BOOKING_REFERENCE");

# LINKS -----------------------------------
insert into ctrl.VAULT_LOAD_LINKS
    (SRC_SYSTEM_NAME, SRC_TABLE_NAME, LINK_RUN_SEQUENCE, SRC_LINK_TABLE_NAME, TGT_LINK_TABLE_NAME, SRC_PK, TGT_PK, SRC_FK, TGT_FK)
values
    ("TLINK", "BOOKINGS", 1, "STG_BOOKINGS", "LINK_BOOKING_PARTY_ROLE", "BPR_CUSTOMER_HASH", "BOOKING_PARTY_ROLE_HASH", "BOOKING_HASH,CUSTOMER_HASH,'CUSTOMER'", "BOOKING_HASH,PARTY_HASH,PARTY_ROLE"), 
    ("TLINK", "BOOKINGS", 2, "STG_BOOKINGS", "LINK_BOOKING_PARTY_ROLE", "BPR_SUPPLIER_HASH", "BOOKING_PARTY_ROLE_HASH", "BOOKING_HASH,SUPPLIER_HASH,'SUPPLIER'", "BOOKING_HASH,PARTY_HASH,PARTY_ROLE"),
    ("TLINK", "BOOKINGS", 3, "STG_BOOKINGS", "LINK_BOOKING_PARTY_ROLE", "BPR_PASSENGER_HASH", "BOOKING_PARTY_ROLE_HASH", "BOOKING_HASH,PASSENGER_HASH,'PASSENGER'", "BOOKING_HASH,PARTY_HASH,PARTY_ROLE"),
    ("TLINK", "BOOKINGS", 4, "STG_BOOKINGS", "LINK_BOOKING_CONVERTS", "BOOKING_CONVERTS_HASH", "BOOKING_CONVERTS_HASH", "BOOKING_HASH,QUOTE_HASH", "BOOKING_HASH, QUOTE_HASH");

# SATELLITES ------------------------------
insert into ctrl.VAULT_LOAD_SATS
    (SRC_SYSTEM_NAME, SRC_TABLE_NAME, SAT_RUN_SEQUENCE, SRC_SAT_TABLE_NAME, TGT_SAT_TABLE_NAME, 
    SRC_PK, TGT_PK, PK, 
    SRC_CDC_HASH, TGT_CDC_HASH, CDC_HASH, 
    SRC_PAYLOAD, 
    TGT_PAYLOAD, 
    PAYLOAD, 
    IL_EFFECTIVE_FROM, DIFF_EFFECTIVE_FROM)
values
    ("TLINK", "BOOKINGS", 1, "STG_BOOKINGS", "SAT_TLINK_BOOKING_DETAILS", 
    "A.BOOKING_HASH", "B.BOOKING_HASH", "BOOKING_HASH", 
    "A.BOOKING_DETAILS_PAYLOAD_HASH", "B.CDC_HASH", "CDC_HASH", 
    "A.BDATE,A.BOOKEDBY,A.CANXDATE,A.CONFIRMDATE,A.DEPARTUREDATE,A.DURATION,A.STATUS", 
    "B.BOOKING_DATE,B.BOOKED_BY,B.CANCELLATION_DATE,B.CONFIRM_DATE,B.DEPARTURE_DATE,B.DURATION,B.STATUS_CODE", 
    "BOOKING_DATE,BOOKED_BY,CANCELLATION_DATE,CONFIRM_DATE,DEPARTURE_DATE,DURATION,STATUS_CODE", 
    "A.LOAD_DATETIME", "A.LOAD_DATETIME"),
    
    ("TLINK", "BOOKINGS", 2, "STG_BOOKINGS", "SAT_TLINK_BOOKING_FINANCIALS", 
    "A.BOOKING_HASH", "B.BOOKING_HASH", "BOOKING_HASH", 
    "A.BOOKING_FINANCIALS_PAYLOAD_HASH", "B.CDC_HASH", "CDC_HASH",  
    "A.ADJ,A.BALANCEDATE,A.MARGIN,A.COM,A.DEP,A.DUE,A.PAY,A.TOT,A.TOTALCOSTS,A.VAT,A.LOCAL_CURRENCY,A.TOMSRATE", 
    "B.ADJUSTMENT_AMOUNT,B.BALANCE_DATE,B.MARGIN_AMOUNT,B.COMMISSION_AMOUNT,B.DEPOSIT_AMOUNT,B.DUE_AMOUNT,B.PAYMENT_AMOUNT,B.TOTAL_PRICE,B.TOTAL_COST,B.VAT_AMOUNT,B.LOCAL_CURRENCY,A.TOMSRATE", 
    "ADJUSTMENT_AMOUNT,BALANCE_DATE,MARGIN_AMOUNT,COMMISSION_AMOUNT,DEPOSIT_AMOUNT,DUE_AMOUNT,PAYMENT_AMOUNT,TOTAL_PRICE,TOTAL_COST,VAT_AMOUNT,LOCAL_CURRENCY,TOMSRATE", 
    "A.LOAD_DATETIME", "A.LOAD_DATETIME"),
    
    ("TLINK", "BOOKINGS", 3, "STG_BOOKINGS", "SAT_TLINK_BOOKING_PAX", 
    "A.BOOKING_HASH", "B.BOOKING_HASH", "BOOKING_HASH", 
    "A.BOOKING_PAX_PAYLOAD_HASH", "B.CDC_HASH", "CDC_HASH",  
    "A.ADULTS,A.CHILDREN,A.INFANTS, A.PAXNUM,A.SEATS", 
    "B.ADULT_COUNT,B.CHILD_COUNT,B.INFANT_COUNT,B.PAX_COUNT,B.SEAT_COUNT", 
    "ADULT_COUNT,CHILD_COUNT,INFANT_COUNT,PAX_COUNT,SEAT_COUNT", 
    "A.LOAD_DATETIME", "A.LOAD_DATETIME"),
    
    ("TLINK", "BOOKINGS", 4, "STG_BOOKINGS", "SAT_TLINK_BOOKING_BOOKING_EFFECTIVITY", 
    "A.BOOKING_HASH", "B.BOOKING_HASH", "BOOKING_HASH", 
    "md5('LIVE')", "B.CDC_HASH", "CDC_HASH",  
    " 'LIVE' ", "B.STATUS", "STATUS", 
    "A.LOAD_DATETIME", "A.LOAD_DATETIME"),
    
    ("TLINK", "BOOKINGS", 5, "STG_BOOKINGS", "SAT_TLINK_BOOKING_BOOKING_PARTY_ROLE_EFFECTIVITY",
    "A.BPR_CUSTOMER_HASH", "B.BOOKING_PARTY_ROLE_HASH", "BOOKING_PARTY_ROLE_HASH",
    "md5('LIVE')", "B.CDC_HASH", "CDC_HASH",
    " 'LIVE' ", "B.STATUS", "STATUS", 
    "A.LOAD_DATETIME", "A.LOAD_DATETIME"),
    
    ("TLINK", "BOOKINGS", 6, "STG_BOOKINGS", "SAT_TLINK_BOOKING_BOOKING_PARTY_ROLE_EFFECTIVITY",
    "A.BPR_SUPPLIER_HASH", "B.BOOKING_PARTY_ROLE_HASH", "BOOKING_PARTY_ROLE_HASH",
    "md5('LIVE')", "B.CDC_HASH", "CDC_HASH",
    " 'LIVE' ", "B.STATUS", "STATUS",
    "A.LOAD_DATETIME", "A.LOAD_DATETIME"),

    ("TLINK", "BOOKINGS", 7, "STG_BOOKINGS", "SAT_TLINK_BOOKING_BOOKING_PARTY_ROLE_EFFECTIVITY",
    "A.BPR_PASSENGER_HASH", "B.BOOKING_PARTY_ROLE_HASH", "BOOKING_PARTY_ROLE_HASH",
    "md5('LIVE')", "B.CDC_HASH", "CDC_HASH",
    " 'LIVE' ", "B.STATUS", "STATUS",
    "A.LOAD_DATETIME", "A.LOAD_DATETIME"),

    ("TLINK", "BOOKINGS", 8, "STG_BOOKINGS", "SAT_TLINK_BOOKING_BOOKING_CONVERTS_EFFECTIVITY",
    "A.BOOKING_CONVERTS_HASH", "B.BOOKING_CONVERTS_HASH", "BOOKING_CONVERTS_HASH",
    "md5('LIVE')", "B.CDC_HASH", "CDC_HASH",
    " 'LIVE' ", "B.STATUS", "STATUS",
    "A.LOAD_DATETIME", "A.LOAD_DATETIME"),

    ("TLINK", "BOOKINGS", 9, "STG_BOOKINGS", "SAT_TLINK_BOOKING_PARTY_EFFECTIVITY",
    "A.CUSTOMER_HASH", "B.PARTY_HASH", "PARTY_HASH",
    "md5('LIVE')", "B.CDC_HASH", "CDC_HASH",
    " 'LIVE' ", "B.STATUS", "STATUS",
    "A.LOAD_DATETIME", "A.LOAD_DATETIME"),

    ("TLINK", "BOOKINGS", 10, "STG_BOOKINGS", "SAT_TLINK_BOOKING_PARTY_EFFECTIVITY",
    "A.PASSENGER_HASH", "B.PARTY_HASH", "PARTY_HASH",
    "md5('LIVE')", "B.CDC_HASH", "CDC_HASH",
    " 'LIVE' ", "B.STATUS", "STATUS",
    "A.LOAD_DATETIME", "A.LOAD_DATETIME"),

    ("TLINK", "BOOKINGS", 11, "STG_BOOKINGS", "SAT_TLINK_BOOKING_PARTY_EFFECTIVITY",
    "A.SUPPLIER_HASH", "B.PARTY_HASH", "PARTY_HASH",
    "md5('LIVE')", "B.CDC_HASH", "CDC_HASH",
    " 'LIVE' ", "B.STATUS", "STATUS",
    "A.LOAD_DATETIME", "A.LOAD_DATETIME"),

    ("TLINK", "BOOKINGS", 12, "STG_BOOKINGS", "SAT_TLINK_BOOKING_BOOKING_PARTY_ROLE_DETAILS",
    "A.BPR_PASSENGER_HASH", "B.BOOKING_PARTY_ROLE_HASH", "BOOKING_PARTY_ROLE_HASH", 
    "A.BOOKING_PARTY_PASSENGER_PAYLOAD_HASH", "B.CDC_HASH", "CDC_HASH", 
    "'1'", 
    "B.IS_LEAD", 
    "IS_LEAD", 
    "A.LOAD_DATETIME", "A.LOAD_DATETIME");

# DELETES ---------------------------------
Insert into ctrl.VAULT_DELETES
    (SYSTEM_NAME, TABLE_NAME, DEL_RUN_SEQUENCE, STG_TABLE_NAME, SRC_COLUMN_FOR_END_DATE, TGT_SATELLITE, SRC_PK, TGT_PK)
values
    ("TLINK", "BOOKINGS", 1, "STG_BOOKINGS", "LOAD_DATETIME", "SAT_TLINK_BOOKING_DETAILS", "BOOKING_HASH", "BOOKING_HASH"),
    ("TLINK", "BOOKINGS", 2, "STG_BOOKINGS", "LOAD_DATETIME", "SAT_TLINK_BOOKING_FINANCIALS", "BOOKING_HASH", "BOOKING_HASH"),
    ("TLINK", "BOOKINGS", 3, "STG_BOOKINGS", "LOAD_DATETIME", "SAT_TLINK_BOOKING_PAX", "BOOKING_HASH", "BOOKING_HASH"),
    ("TLINK", "BOOKINGS", 4, "STG_BOOKINGS", "LOAD_DATETIME", "SAT_TLINK_BOOKING_PARTY_ROLE_DETAILS", "BPR_PASSENGER_HASH", "BOOKING_PARTY_ROLE_HASH");

# DELETE EFFECTIVITY ----------------------
insert into ctrl.VAULT_DELETE_EFFECTIVITY
    (SRC_SYSTEM_NAME, SRC_TABLE_NAME, EFF_DEL_RUN_SEQUENCE, SRC_SAT_TABLE_NAME, TGT_SAT_TABLE_NAME, SRC_PK, TGT_PK, PK, SRC_CDC_HASH, TGT_CDC_HASH, CDC_HASH, 
    SRC_PAYLOAD, TGT_PAYLOAD, PAYLOAD, IL_EFFECTIVE_FROM, DIFF_EFFECTIVE_FROM)
values
    ("TLINK", "BOOKINGS", 1, "STG_BOOKINGS", "SAT_TLINK_BOOKING_BOOKING_EFFECTIVITY", "A.BOOKING_HASH", "B.BOOKING_HASH", "BOOKING_HASH", 
    "md5('DELETED')", "B.CDC_HASH", "CDC_HASH", 
    " 'DELETED' ", "B.STATUS", "STATUS", "A.LOAD_DATETIME", "A.LOAD_DATETIME"),
    ("TLINK", "BOOKINGS", 2, "STG_BOOKINGS", "SAT_TLINK_BOOKING_BOOKING_PARTY_ROLE_EFFECTIVITY", "A.BPR_CUSTOMER_HASH", "B.BOOKING_PARTY_ROLE_HASH", "BOOKING_PARTY_ROLE_HASH", 
    "md5('DELETED')", "B.CDC_HASH", "CDC_HASH",
    " 'DELETED' ", "B.STATUS", "STATUS", "A.LOAD_DATETIME", "A.LOAD_DATETIME"),
    ("TLINK", "BOOKINGS", 3, "STG_BOOKINGS", "SAT_TLINK_BOOKING_BOOKING_PARTY_ROLE_EFFECTIVITY", "A.BPR_SUPPLIER_HASH", "B.BOOKING_PARTY_ROLE_HASH", "BOOKING_PARTY_ROLE_HASH", 
    "md5('DELETED')", "B.CDC_HASH", "CDC_HASH", 
    " 'DELETED' ", "B.STATUS", "STATUS", "A.LOAD_DATETIME", "A.LOAD_DATETIME"),
    ("TLINK", "BOOKINGS", 4, "STG_BOOKINGS", "SAT_TLINK_BOOKING_BOOKING_PARTY_ROLE_EFFECTIVITY", "A.BPR_PASSENGER_HASH", "B.BOOKING_PARTY_ROLE_HASH", "BOOKING_PARTY_ROLE_HASH", 
    "md5('DELETED')", "B.CDC_HASH", "CDC_HASH", 
    " 'DELETED' ", "B.STATUS", "STATUS", "A.LOAD_DATETIME", "A.LOAD_DATETIME"),
    ("TLINK", "BOOKINGS", 5, "STG_BOOKINGS", "SAT_TLINK_BOOKING_BOOKING_CONVERTS_EFFECTIVITY", "A.BOOKING_CONVERTS_HASH", "B.BOOKING_CONVERTS_HASH", "BOOKING_CONVERTS_HASH", 
    "md5('DELETED')", "B.CDC_HASH", "CDC_HASH", 
    " 'DELETED' ", "B.STATUS", "STATUS", "A.LOAD_DATETIME", "A.LOAD_DATETIME"),
    ("TLINK", "BOOKINGS", 6, "STG_BOOKINGS", "SAT_TLINK_BOOKING_PARTY_EFFECTIVITY", "A.PASSENGER_HASH", "B.PARTY_HASH", "PARTY_HASH", 
    "md5('DELETED')", "B.CDC_HASH", "CDC_HASH", 
    " 'DELETED' ", "B.STATUS", "STATUS", "A.LOAD_DATETIME", "A.LOAD_DATETIME"),
    ("TLINK", "BOOKINGS", 7, "STG_BOOKINGS", "SAT_TLINK_BOOKING_PARTY_EFFECTIVITY", "A.SUPPLIER_HASH", "B.PARTY_HASH", "PARTY_HASH", 
    "md5('DELETED')", "B.CDC_HASH", "CDC_HASH", 
    " 'DELETED' ", "B.STATUS", "STATUS", "A.LOAD_DATETIME", "A.LOAD_DATETIME"),
    ("TLINK", "BOOKINGS", 8, "STG_BOOKINGS", "SAT_TLINK_BOOKING_PARTY_EFFECTIVITY", "A.CUSTOMER_HASH", "B.PARTY_HASH", "PARTY_HASH", 
    "md5('DELETED')", "B.CDC_HASH", "CDC_HASH", 
    " 'DELETED' ", "B.STATUS", "STATUS", "A.LOAD_DATETIME", "A.LOAD_DATETIME");

# DELETE FK EFFECTIVITY -------------------
insert into ctrl.VAULT_DELETE_FK_LINK_EFFECTIVITY
    (SRC_SYSTEM_NAME, SRC_TABLE_NAME, FK_EFF_DEL_RUN_SEQUENCE, SRC_SAT_TABLE_NAME, TGT_SAT_TABLE_NAME, SRC_PK, TGT_PK, PK, SRC_CDC_HASH, TGT_CDC_HASH, CDC_HASH, 
    SRC_PAYLOAD, PAYLOAD, IL_EFFECTIVE_FROM, DIFF_EFFECTIVE_FROM, PARENT_HASH, SRC_LINK_TABLE_NAME, DRIVING_JOIN_CONDITION, SECONDARY_JOIN_CONDITION)
values 
    ("TLINK", "BOOKINGS", 1, "STG_BOOKINGS","SAT_TLINK_BOOKING_BOOKING_PARTY_ROLE_EFFECTIVITY", "A.BPR_CUSTOMER_HASH", "B.BOOKING_PARTY_ROLE_HASH", "BOOKING_PARTY_ROLE_HASH", 
    "md5('DELETED') ", "B.CDC_HASH", "CDC_HASH", " 'DELETED' ", "STATUS", "STG.LOAD_DATETIME", "STG.LOAD_DATETIME", 
    "BOOKING_PARTY_ROLE_HASH", "LINK_BOOKING_PARTY_ROLE", "A.BOOKING_HASH = STG.BOOKING_HASH and A.PARTY_ROLE = 'CUSTOMER'", "A.PARTY_HASH <> STG.CUSTOMER_HASH"),
    ("TLINK", "BOOKINGS", 2, "STG_BOOKINGS", "SAT_TLINK_BOOKING_BOOKING_PARTY_ROLE_EFFECTIVITY", "A.BPR_SUPPLIER_HASH", "B.BOOKING_PARTY_ROLE_HASH", "BOOKING_PARTY_ROLE_HASH", 
    "md5('DELETED')", "B.CDC_HASH", "CDC_HASH", " 'DELETED' ", "STATUS", "STG.LOAD_DATETIME", "STG.LOAD_DATETIME", 
    "BOOKING_PARTY_ROLE_HASH", "LINK_BOOKING_PARTY_ROLE", "A.BOOKING_HASH = STG.BOOKING_HASH and A.PARTY_ROLE = 'SUPPLIER'", "A.PARTY_HASH <> STG.SUPPLIER_HASH"),
    ("TLINK", "BOOKINGS", 3, "STG_BOOKINGS", "SAT_TLINK_BOOKING_BOOKING_PARTY_ROLE_EFFECTIVITY", "A.BPR_PASSENGER_HASH", "B.BOOKING_PARTY_ROLE_HASH", "BOOKING_PARTY_ROLE_HASH", 
    "md5('DELETED')", "B.CDC_HASH", "CDC_HASH", " 'DELETED' ", "STATUS", "STG.LOAD_DATETIME", "STG.LOAD_DATETIME", 
    "BOOKING_PARTY_ROLE_HASH", "LINK_BOOKING_PARTY_ROLE", "A.BOOKING_HASH = STG.BOOKING_HASH and A.PARTY_ROLE = 'PASSENGER'", "A.PARTY_HASH <> STG.PASSENGER_HASH"),
    ("TLINK", "BOOKINGS", 4, "STG_BOOKINGS", "SAT_TLINK_BOOKING_BOOKING_CONVERTS_EFFECTIVITY", "A.BOOKING_CONVERTS_HASH", "B.BOOKING_CONVERTS_HASH", "BOOKING_CONVERTS_HASH", 
    "md5('DELETED')", "B.CDC_HASH", "CDC_HASH", " 'DELETED' ", "STATUS", "STG.LOAD_DATETIME", "STG.LOAD_DATETIME", 
    "BOOKING_CONVERTS_HASH", "LINK_BOOKING_CONVERTS", "A.BOOKING_HASH = STG.BOOKING_HASH", "A.BOOKING_CONVERTS_HASH <> STG.BOOKING_CONVERTS_HASH");

# -----------------------------------------------------------------------------------------------------------------------------------------
# TRAVELINK - AGENCY
# -----------------------------------------------------------------------------------------------------------------------------------------

# HASHES ----------------------------------
insert into ctrl.VAULT_LOAD_HASHES (SRC_SYSTEM_NAME, SRC_TABLE_NAME, HASH_RUN_SEQUENCE, TGT_TABLE_NAME, COLUMNS_USED_FOR_HASH, TGT_HASH_COLUMN)
values
    ("TLINK", "STG_AGENCY", 1, "STG_AGENCY", "'TLINK-CUSTOMER-CODES', ABTA", "AGENCY_HASH"), -- for hub parties, customer records
    ("TLINK", "STG_AGENCY", 2, "STG_AGENCY", "'TELEPHONE', TELEPHONE", "LOCATOR_TELEPHONE_HASH"),   --  for phone number
    ("TLINK", "STG_AGENCY", 3, "STG_AGENCY", "'TELEPHONE', FAX", "LOCATOR_FAX_HASH"),   -- for fax number
    ("TLINK", "STG_AGENCY", 4, "STG_AGENCY", "'POSTAL ADDRESS', ADD1, ADD2, ADD3, COUNTY, COUNTRY, POSTCODE, TOWN_CITY", "LOCATOR_POSTAL_ADDRESS_HASH"),  -- for postal address
    ("TLINK", "STG_AGENCY", 5, "STG_AGENCY", "'TLINK-CUSTOMER-CODES', ABTA, 'TELEPHONE', TELEPHONE", "PARTY_CONTACT_TELEPHONE_HASH"),   -- for telephone contact link to party
    ("TLINK", "STG_AGENCY", 6, "STG_AGENCY", "'TLINK-CUSTOMER-CODES', ABTA, 'TELEPHONE', FAX", "PARTY_CONTACT_FAX_HASH"),   -- for fax contact link to party
    ("TLINK", "STG_AGENCY", 7, "STG_AGENCY", "'TLINK-CUSTOMER-CODES', ABTA, 'POSTAL ADDRESS', ADD1, ADD2, ADD3, COUNTY, COUNTRY, POSTCODE", "PARTY_CONTACT_POSTAL_ADDRESS_HASH"), -- for postal address link to party
    ("TLINK", "STG_AGENCY", 8, "STG_AGENCY", "AGENCY_REGION", "REGION_HASH"),  -- geographic region hash, type resort
    ("TLINK", "STG_AGENCY", 9, "STG_AGENCY", "'TLINK-CUSTOMER-CODES', ABTA, AGENCY_REGION", "PARTY_REGION_HASH"),   -- for linking region to party
    ("TLINK", "STG_AGENCY",10, "STG_AGENCY", "ABTA, AGENCYABTA, AGENCYID, AGENTCEASED, AGID, AGIDPAYMENT, ATOL, CANCELFROMEMAIL, ATOLNUMBER, CONCATENATEDNAME, DATECREATED, DOB, FIRSTNAME, BILLINGTYPE, COMMENTS, COMMTYPE, CREDITLIMIT, GENDER, LASTNAME, SALUTATION, STATUS, TITLE, STOPSALE, VATNUMBER ", "AGENCY_PAYLOAD_HASH"),  -- for sat agency details
    ("TLINK", "STG_AGENCY",11, "STG_AGENCY", "'UNSPECIFIED', TELEPHONE", "LOCATOR_TELEPHONE_PAYLOAD_HASH"),  -- for sat telephone
    ("TLINK", "STG_AGENCY",12, "STG_AGENCY", "'FAX', FAX", "LOCATOR_FAX_PAYLOAD_HASH");   -- for sat fax (telephone)
    ("TLINK", "STG_AGENCY",13, "STG_AGENCY", "ADD1, ADD2, ADD3, COUNTRY, COUNTY, POSTCODE, TOWN_CITY", "LOCATOR_POSTAL_ADDRESS_PAYLOAD_HASH"),   -- for sat postal address
    ("TLINK", "STG_AGENCY",14, "STG_AGENCY", "CANCELFROMMAILING, SUSPENDFROMMAILING", "PARTY_CONTACT_TELEPHONE_PAYLOAD_HASH"),  -- for telephone link to party details (opt in)
    -- >>>>>>>>>>>>> NOTE 15, 16 may be a link to COMMISSION_GROUP not PAYMENT_GROUP - to be researched....
    ("TLINK", "STG_AGENCY",15, "STG_AGENCY", "AGID", "PAYMENT_GROUP_HASH"),  -- for payment group details
    ("TLINK", "STG_AGENCY",16, "STG_AGENCY", "'TLINK-CUSTOMER-CODES', ABTA, AGID", "AGENCY_PAYMENT_GROUP_HASH");   -- for payment group details

# HUBS ------------------------------------
insert into ctrl.VAULT_LOAD_HUBS
    (SRC_SYSTEM_NAME, SRC_TABLE_NAME, HUB_RUN_SEQUENCE, SRC_HUB_TABLE_NAME, TGT_HUB_TABLE_NAME, SRC_PK, TGT_PK, SRC_NK, TGT_NK)
values
    ("TLINK", "AGENCY", 1, "STG_AGENCY", "HUB_PARTY", "AGENCY_HASH", "PARTY_HASH", " 'TLINK-CUSTOMER-CODES',ABTA", "IDENTIFIER_SET, PARTY_REFERENCE"),
    ("TLINK", "AGENCY", 2, "STG_AGENCY", "HUB_LOCATOR", "LOCATOR_TELEPHONE_HASH", "LOCATOR_HASH", " 'TELEPHONE',TELEPHONE", "LOCATOR_TYPE,CONCATENATED_LOCATOR"),
    ("TLINK", "AGENCY", 3, "STG_AGENCY", "HUB_LOCATOR", "LOCATOR_FAX_HASH", "LOCATOR_HASH", " 'TELEPHONE',FAX", "LOCATOR_TYPE,CONCATENATED_LOCATOR"),
    ("TLINK", "AGENCY", 4, "STG_AGENCY", "HUB_LOCATOR", "LOCATOR_POSTAL_ADDRESS_HASH", "LOCATOR_HASH", " 'POSTAL_ADDRESS',concat(ADD1, ADD2, ADD3, COUNTY, COUNTRY, POSTCODE, TOWN_CITY)", "LOCATOR_TYPE,CONCATENATED_LOCATOR"),
    ("TLINK", "AGENCY", 5, "STG_AGENCY", "HUB_GEOGRAPHIC_AREA", "REGION_HASH", "GEOGRAPHIC_AREA_HASH", " 'REGION',AGENCY_REGION", "AREA_TYPE, AREA_NAME");

# LINKS -----------------------------------
insert into ctrl.VAULT_LOAD_LINKS
    (SRC_SYSTEM_NAME, SRC_TABLE_NAME, LINK_RUN_SEQUENCE, SRC_LINK_TABLE_NAME, TGT_LINK_TABLE_NAME, SRC_PK, TGT_PK, SRC_FK, TGT_FK)
values
    ("TLINK", "AGENCY", 1, "STG_AGENCY", "LINK_PARTY_CONTACT", "PARTY_CONTACT_TELEPHONE_HASH", "PARTY_CONTACT_HASH", "AGENCY_HASH,LOCATOR_TELEPHONE_HASH", "PARTY_HASH,LOCATOR_HASH"), 
    ("TLINK", "AGENCY", 2, "STG_AGENCY", "LINK_PARTY_CONTACT", "PARTY_CONTACT_FAX_HASH", "PARTY_CONTACT_HASH", "AGENCY_HASH,LOCATOR_FAX_HASH", "PARTY_HASH,LOCATOR_HASH"), 
    ("TLINK", "AGENCY", 3, "STG_AGENCY", "LINK_PARTY_CONTACT", "PARTY_CONTACT_POSTAL_ADDRESS_HASH", "PARTY_CONTACT_HASH", "AGENCY_HASH,LOCATOR_POSTAL_ADDRESS_HASH", "PARTY_HASH,LOCATOR_HASH"), 
    ("TLINK", "AGENCY", 4, "STG_AGENCY", "LINK_PARTY_GEOGRAPHIC_AREA", "REGION_HASH", "GEOGRAPHIC_AREA_HASH", "AGENCY_HASH, REGION_HASH", "PARTY_HASH,GEOGRAPHIC_AREA_HASH");

# SATELLITES ------------------------------
insert into ctrl.VAULT_LOAD_SATS
    (SRC_SYSTEM_NAME, SRC_TABLE_NAME, SAT_RUN_SEQUENCE, SRC_SAT_TABLE_NAME, TGT_SAT_TABLE_NAME, 
    SRC_PK, TGT_PK, PK, 
    SRC_CDC_HASH, TGT_CDC_HASH, CDC_HASH, 
    SRC_PAYLOAD, 
    TGT_PAYLOAD, 
    PAYLOAD, 
    IL_EFFECTIVE_FROM, DIFF_EFFECTIVE_FROM)
values
    ("TLINK", "AGENCY", 1, "STG_AGENCY", "SAT_TLINK_AGENCY_PARTY_DETAILS", 
    "A.AGENCY_HASH", "B.PARTY_HASH", "PARTY_HASH", 
    "A.AGENCY_PAYLOAD_HASH", "B.CDC_HASH", "CDC_HASH", 
    "A.ABTA, A.AGENCYABTA, A.AGENCYID, A.AGENTCEASED, A.AGID, A.AGIDPAYMENT, A.ATOL, A.CANCELFROMEMAIL, A.ATOLNUMBER, A.CONCATENATEDNAME, A.DATECREATED, A.DOB, A.FIRSTNAME, A.BILLINGTYPE, A.COMMENTS, A.COMMTYPE, A.CREDITLIMIT, A.GENDER, A.LASTNAME, A.SALUTATION, A.STATUS, A.TITLE, A.STOPSALE, A.VATNUMBER",
    "B.ABTA, B.AGENCY_ABTA, B.AGENCY_ID, B.AGENT_CEASED, B.AGID, B.AGID_PAYMENT, B.ATOL, B.CANCEL_FROM_EMAIL, B.ATOL_NUMBER, B.CONCATENATED_NAME, B.DATE_CREATED, B.DATE_OF_BIRTH, B.GIVEN_NAME, B.BILLING_TYPE, B.COMMENTS, B.COMMISSION_TYPE, B.CREDIT_LIMIT, B.GENDER, B.FAMILY_NAME, B.SALUTATION, B.STATUS_CODE, B.TITLE, B.STOP_SALE, B.VAT_NUMBER",
    "ABTA, AGENCY_ABTA, AGENCY_ID, AGENT_CEASED, AGID, AGID_PAYMENT, ATOL, CANCEL_FROM_EMAIL, ATOL_NUMBER, CONCATENATED_NAME, DATE_CREATED, DATE_OF_BIRTH, GIVEN_NAME, BILLING_TYPE, COMMENTS, COMMISSION_TYPE, CREDIT_LIMIT, GENDER, FAMILY_NAME, SALUTATION, STATUS_CODE, TITLE, STOP_SALE, VAT_NUMBER",
    "A.LOAD_DATETIME", "A.LOAD_DATETIME"),

    ("TLINK", "AGENCY", 2, "STG_AGENCY", "SAT_TLINK_AGENCY_TELEPHONE", 
    "A.LOCATOR_TELEPHONE_HASH", "B.LOCATOR_HASH", "LOCATOR_HASH", 
    "A.LOCATOR_TELEPHONE_PAYLOAD_HASH", "B.CDC_HASH", "CDC_HASH",  
    "A.TELEPHONE, 'UNSPECIFIED'", 
    "B.TELEPHONE, B.DEVICE_TYPE", 
    "TELEPHONE, DEVICE_TYPE", 
    "A.LOAD_DATETIME", "A.LOAD_DATETIME"),

    ("TLINK", "AGENCY", 3, "STG_AGENCY", "SAT_TLINK_AGENCY_TELEPHONE", 
    "A.LOCATOR_FAX_HASH", "B.LOCATOR_HASH", "LOCATOR_HASH", 
    "A.LOCATOR_FAX_PAYLOAD_HASH", "B.CDC_HASH", "CDC_HASH",  
    "A.FAX, 'FAX'", 
    "B.TELEPHONE, B.DEVICE_TYPE", 
    "TELEPHONE, DEVICE_TYPE", 
    "A.LOAD_DATETIME", "A.LOAD_DATETIME"),

    ("TLINK", "AGENCY", 4, "STG_AGENCY", "SAT_TLINK_AGENCY_POSTAL_ADDRESS", 
    "A.LOCATOR_POSTAL_ADDRESS_HASH", "B.LOCATOR_HASH", "LOCATOR_HASH", 
    "A.LOCATOR_POSTAL_ADDRESS_PAYLOAD_HASH", "B.CDC_HASH", "CDC_HASH",  
    "A.ADD1, A.ADD2, A.ADD3, A.COUNTY, A.COUNTRY, A.POSTCODE, A.TOWN_CITY", 
    "B.ADDRESS_LINE_1, B.ADDRESS_LINE_2, B.ADDRESS_LINE_3, B.COUNTY, B.COUNTRY, B.POST_CODE, B.TOWN_CITY", 
    "ADDRESS_LINE_1, ADDRESS_LINE_2, ADDRESS_LINE_3, COUNTY, COUNTRY, POST_CODE, TOWN_CITY", 
    "A.LOAD_DATETIME", "A.LOAD_DATETIME"),

    ("TLINK", "AGENCY", 5, "STG_AGENCY", "SAT_TLINK_AGENCY_PARTY_EFFECTIVITY", 
    "A.AGENCY_HASH", "B.PARTY_HASH", "PARTY_HASH", 
    "md5('LIVE')", "B.CDC_HASH", "CDC_HASH",  
    " 'LIVE' ", "B.STATUS", "STATUS", 
    "A.LOAD_DATETIME", "A.LOAD_DATETIME"),

    ("TLINK", "AGENCY", 6, "STG_AGENCY", "SAT_TLINK_AGENCY_LOCATOR_EFFECTIVITY", 
    "A.LOCATOR_TELEPHONE_HASH", "B.LOCATOR_HASH", "LOCATOR_HASH", 
    "md5('LIVE')", "B.CDC_HASH", "CDC_HASH",  
    " 'LIVE' ", "B.STATUS", "STATUS", 
    "A.LOAD_DATETIME", "A.LOAD_DATETIME"),

    ("TLINK", "AGENCY", 7, "STG_AGENCY", "SAT_TLINK_AGENCY_LOCATOR_EFFECTIVITY", 
    "A.LOCATOR_FAX_HASH", "B.LOCATOR_HASH", "LOCATOR_HASH", 
    "md5('LIVE')", "B.CDC_HASH", "CDC_HASH",  
    " 'LIVE' ", "B.STATUS", "STATUS", 
    "A.LOAD_DATETIME", "A.LOAD_DATETIME"),

    ("TLINK", "AGENCY", 8, "STG_AGENCY", "SAT_TLINK_AGENCY_LOCATOR_EFFECTIVITY", 
    "A.LOCATOR_POSTAL_ADDRESS_HASH", "B.LOCATOR_HASH", "LOCATOR_HASH", 
    "md5('LIVE')", "B.CDC_HASH", "CDC_HASH",  
    " 'LIVE' ", "B.STATUS", "STATUS", 
    "A.LOAD_DATETIME", "A.LOAD_DATETIME"),

    ("TLINK", "AGENCY", 9, "STG_AGENCY", "SAT_TLINK_AGENCY_PARTY_CONTACT_EFFECTIVITY", 
    "A.PARTY_CONTACT_TELEPHONE_HASH", "B.LOCATOR_HASH", "LOCATOR_HASH", 
    "md5('LIVE')", "B.CDC_HASH", "CDC_HASH",  
    " 'LIVE' ", "B.STATUS", "STATUS", 
    "A.LOAD_DATETIME", "A.LOAD_DATETIME"),

    ("TLINK", "AGENCY", 10, "STG_AGENCY", "SAT_TLINK_AGENCY_PARTY_CONTACT_EFFECTIVITY", 
    "A.PARTY_CONTACT_FAX_HASH", "B.LOCATOR_HASH", "LOCATOR_HASH", 
    "md5('LIVE')", "B.CDC_HASH", "CDC_HASH",  
    " 'LIVE' ", "B.STATUS", "STATUS", 
    "A.LOAD_DATETIME", "A.LOAD_DATETIME"),

    ("TLINK", "AGENCY", 11, "STG_AGENCY", "SAT_TLINK_AGENCY_PARTY_CONTACT_EFFECTIVITY", 
    "A.PARTY_CONTACT_POSTAL_ADDRESS_HASH", "B.LOCATOR_HASH", "LOCATOR_HASH", 
    "md5('LIVE')", "B.CDC_HASH", "CDC_HASH",  
    " 'LIVE' ", "B.STATUS", "STATUS", 
    "A.LOAD_DATETIME", "A.LOAD_DATETIME"),

    ("TLINK", "AGENCY", 12, "STG_AGENCY", "SAT_TLINK_AGENCY_PARTY_GEOGRAPHIC_AREA_EFFECTIVITY", 
    "A.PARTY_REGION_HASH", "B.LOCATOR_HASH", "LOCATOR_HASH", 
    "md5('LIVE')", "B.CDC_HASH", "CDC_HASH",  
    " 'LIVE' ", "B.STATUS", "STATUS", 
    "A.LOAD_DATETIME", "A.LOAD_DATETIME");

# DELETES ---------------------------------
Insert into ctrl.VAULT_DELETES
    (SYSTEM_NAME, TABLE_NAME, DEL_RUN_SEQUENCE, STG_TABLE_NAME, SRC_COLUMN_FOR_END_DATE, TGT_SATELLITE, SRC_PK, TGT_PK)
values
    ("TLINK", "AGENCY", 1, "STG_AGENCY", "LOAD_DATETIME", "SAT_TLINK_AGENCY_PARTY_DETAILS", "AGENCY_HASH", "PARTY_HASH"),
    ("TLINK", "AGENCY", 2, "STG_AGENCY", "LOAD_DATETIME", "SAT_TLINK_AGENCY_TELEPHONE", "LOCATOR_TELEPHONE_HASH", "LOCATOR_HASH"),
    ("TLINK", "AGENCY", 3, "STG_AGENCY", "LOAD_DATETIME", "SAT_TLINK_AGENCY_TELEPHONE", "LOCATOR_FAX_HASH", "LOCATOR_HASH"),
    ("TLINK", "AGENCY", 4, "STG_AGENCY", "LOAD_DATETIME", "SAT_TLINK_AGENCY_POSTAL_ADDRESS", "LOCATOR_POSTAL_ADDRESS_HASH", "LOCATOR_HASH"),
    ("TLINK", "AGENCY", 5, "STG_AGENCY", "LOAD_DATETIME", "SAT_TLINK_AGENCY_PARTY_CONTACT", "PARTY_CONTACT_POSTAL_ADDRESS_HASH", "PARTY_CONTACT_HASH");

# DELETE EFFECTIVITY ----------------------
insert into ctrl.VAULT_DELETE_EFFECTIVITY
    (SRC_SYSTEM_NAME, SRC_TABLE_NAME, EFF_DEL_RUN_SEQUENCE, SRC_SAT_TABLE_NAME, TGT_SAT_TABLE_NAME, SRC_PK, TGT_PK, PK, SRC_CDC_HASH, TGT_CDC_HASH, CDC_HASH, 
    SRC_PAYLOAD, TGT_PAYLOAD, PAYLOAD, IL_EFFECTIVE_FROM, DIFF_EFFECTIVE_FROM)
values
    ("TLINK", "AGENCY", 1, "STG_AGENCY", "SAT_TLINK_AGENCY_PARTY_EFFECTIVITY", "A.AGENCY_HASH", "B.PARTY_HASH", "PARTY_HASH", 
    "md5('DELETED')", "B.CDC_HASH", "CDC_HASH", 
    " 'DELETED' ", "B.STATUS", "STATUS", "A.LOAD_DATETIME", "A.LOAD_DATETIME"),
    ("TLINK", "AGENCY", 2, "STG_AGENCY", "SAT_TLINK_AGENCY_LOCATOR_EFFECTIVITY", "A.LOCATOR_TELEPHONE_HASH", "B.LOCATOR_HASH", "LOCATOR_HASH", 
    "md5('DELETED')", "B.CDC_HASH", "CDC_HASH",
    " 'DELETED' ", "B.STATUS", "STATUS", "A.LOAD_DATETIME", "A.LOAD_DATETIME"),
    ("TLINK", "AGENCY", 3, "STG_AGENCY", "SAT_TLINK_AGENCY_LOCATOR_EFFECTIVITY", "A.LOCATOR_FAX_HASH", "B.LOCATOR_HASH", "LOCATOR_HASH", 
    "md5('DELETED')", "B.CDC_HASH", "CDC_HASH",
    " 'DELETED' ", "B.STATUS", "STATUS", "A.LOAD_DATETIME", "A.LOAD_DATETIME"),
    ("TLINK", "AGENCY", 4, "STG_AGENCY", "SAT_TLINK_AGENCY_LOCATOR_EFFECTIVITY", "A.LOCATOR_POSTAL_ADDRESS_HASH", "B.LOCATOR_HASH", "LOCATOR_HASH", 
    "md5('DELETED')", "B.CDC_HASH", "CDC_HASH",
    " 'DELETED' ", "B.STATUS", "STATUS", "A.LOAD_DATETIME", "A.LOAD_DATETIME"),
    ("TLINK", "AGENCY", 5, "STG_AGENCY", "SAT_TLINK_AGENCY_PARTY_GEOGRAPHIC_AREA_EFFECTIVITY", "A.PARTY_REGION_HASH", "B.PARTY_GEOGRAPHIC_AREA_HASH", "GEOGRAPHIC_AREA_HASH", 
    "md5('DELETED')", "B.CDC_HASH", "CDC_HASH",
    " 'DELETED' ", "B.STATUS", "STATUS", "A.LOAD_DATETIME", "A.LOAD_DATETIME");
    ("TLINK", "AGENCY", 6, "STG_AGENCY", "SAT_TLINK_AGENCY_PARTY_CONTACT_EFFECTIVITY", "A.PARTY_CONTACT_TELEPHONE_HASH", "B.PARTY_CONTACT_HASH", "PARTY_CONTACT_HASH", 
    "md5('DELETED')", "B.CDC_HASH", "CDC_HASH",
    " 'DELETED' ", "B.STATUS", "STATUS", "A.LOAD_DATETIME", "A.LOAD_DATETIME"),
    ("TLINK", "AGENCY", 7, "STG_AGENCY", "SAT_TLINK_AGENCY_PARTY_CONTACT_EFFECTIVITY", "A.PARTY_CONTACT_FAX_HASH", "B.PARTY_CONTACT_HASH", "PARTY_CONTACT_HASH", 
    "md5('DELETED')", "B.CDC_HASH", "CDC_HASH",
    " 'DELETED' ", "B.STATUS", "STATUS", "A.LOAD_DATETIME", "A.LOAD_DATETIME"),
    ("TLINK", "AGENCY", 8, "STG_AGENCY", "SAT_TLINK_AGENCY_PARTY_CONTACT_EFFECTIVITY", "A.PARTY_CONTACT_POSTAL_ADDRESS_HASH", "B.PARTY_CONTACT_HASH", "PARTY_CONTACT_HASH", 
    "md5('DELETED')", "B.CDC_HASH", "CDC_HASH",
    " 'DELETED' ", "B.STATUS", "STATUS", "A.LOAD_DATETIME", "A.LOAD_DATETIME");

# DELETE FK EFFECTIVITY -------------------
insert into ctrl.VAULT_DELETE_FK_LINK_EFFECTIVITY
    (SRC_SYSTEM_NAME, SRC_TABLE_NAME, FK_EFF_DEL_RUN_SEQUENCE, SRC_SAT_TABLE_NAME, TGT_SAT_TABLE_NAME, SRC_PK, TGT_PK, PK, SRC_CDC_HASH, TGT_CDC_HASH, CDC_HASH, 
    SRC_PAYLOAD, PAYLOAD, IL_EFFECTIVE_FROM, DIFF_EFFECTIVE_FROM, PARENT_HASH, SRC_LINK_TABLE_NAME, DRIVING_JOIN_CONDITION, SECONDARY_JOIN_CONDITION)
values 
    ("TLINK", "AGENCY", 1, "STG_AGENCY","SAT_TLINK_AGENCY_LOCATOR_EFFECTIVITY", "A.PARTY_CONTACT_TELEPHONE_HASH", "B.PARTY_CONTACT_HASH", "PARTY_CONTACT_HASH", 
    "md5('DELETED') ", "B.CDC_HASH", "CDC_HASH", " 'DELETED' ", "STATUS", "STG.LOAD_DATETIME", "STG.LOAD_DATETIME", 
    "PARTY_CONTACT_HASH", "LINK_PARTY_CONTACT", "A.PARTY_HASH = STG.AGENCY_HASH", "A.LOCATOR_HASH <> STG.LOCATOR_TELEPHONE_HASH"),
    ("TLINK", "AGENCY", 2, "STG_AGENCY","SAT_TLINK_AGENCY_LOCATOR_EFFECTIVITY", "A.PARTY_CONTACT_FAX_HASH", "B.PARTY_CONTACT_HASH", "PARTY_CONTACT_HASH", 
    "md5('DELETED') ", "B.CDC_HASH", "CDC_HASH", " 'DELETED' ", "STATUS", "STG.LOAD_DATETIME", "STG.LOAD_DATETIME", 
    "PARTY_CONTACT_HASH", "LINK_PARTY_CONTACT", "A.PARTY_HASH = STG.AGENCY_HASH", "A.LOCATOR_HASH <> STG.LOCATOR_FAX_HASH"),
    ("TLINK", "AGENCY", 3, "STG_AGENCY","SAT_TLINK_AGENCY_LOCATOR_EFFECTIVITY", "A.PARTY_CONTACT_POSTAL_ADDRESS_HASH", "B.PARTY_CONTACT_HASH", "PARTY_CONTACT_HASH", 
    "md5('DELETED') ", "B.CDC_HASH", "CDC_HASH", " 'DELETED' ", "STATUS", "STG.LOAD_DATETIME", "STG.LOAD_DATETIME", 
    "PARTY_CONTACT_HASH", "LINK_PARTY_CONTACT", "A.PARTY_HASH = STG.AGENCY_HASH", "A.LOCATOR_HASH <> STG.LOCATOR_POSTAL_ADDRESS_HASH"),
    ("TLINK", "AGENCY", 4, "STG_AGENCY","SAT_TLINK_AGENCY_PARTY_GEOGRAPHIC_AREA_EFFECTIVITY", "A.PARTY_REGION_HASH", "B.PARTY_GEOGRAPHIC_AREA_HASH", "GEOGRAPHIC_AREA_HASH", 
    "md5('DELETED') ", "B.CDC_HASH", "CDC_HASH", " 'DELETED' ", "STATUS", "STG.LOAD_DATETIME", "STG.LOAD_DATETIME", 
    "PARTY_GEOGRAPHIC_AREA_HASH", "LINK_PARTY_GEOGRAPHIC_AREA", "A.PARTY_HASH = STG.AGENCY_HASH", "A.LOCATOR_HASH <> STG.REGION_HASH");


# =========================================================================================================================================
# TRAVELINK - END
# =========================================================================================================================================